apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ebanking
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: e-banking Project
  destinations:
    - namespace: ebanking
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/Khadija-Laamiri/e-banking-api-manifest
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
