apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: ebanking
  source:
    repoURL: https://github.com/Khadija-Laamiri/e-banking-api-manifest
    targetRevision: HEAD
    path: postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: ebanking
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true