apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery-container
          image: enamifatimazahrae2001/discovery:v0.4
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  clusterIP: None
