apiVersion: apps/v1
kind: Deployment
metadata:
  name: facture-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facture
  template:
    metadata:
      labels:
        app: facture
    spec:
      containers:
        - name: user-container
          image: enamifatimazahrae2001/facture:v0.4
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: facture-service
spec:
  selector:
    app: facture
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  clusterIP: None
