apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-transaction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-transaction
  template:
    metadata:
      labels:
        app: payment-transaction
    spec:
      containers:
        - name: payment-transaction-container
          image: enamifatimazahrae2001/payment-transaction:v0.6
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: payment-transaction-service
spec:
  selector:
    app: payment-transaction
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  clusterIP: None
