apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: enamifatimazahrae2001/user:v0.15
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  clusterIP: None
